### ISSUE TITLE
Retrieving full data using Activision platform does not find user. (Any COD Game) 

### ISSUE THREAD

**Issue by kilgoreandy** [TodoLodo/cod-python-api#9]
This is a valid Activision account, (I tried a few more Activision accounts and they also did not work) 
I of course can go the playstation route and retrieve the data that way, however the Activision un is more universal and reliable 

Reproduction code:
import asyncio

from cod_api import API, platforms
async def main():
    # initiating the API class
    api = API()
    api.login('haha')

    # retrieving combat history
    profile = await api.ColdWar.fullData(platforms.Activision, "ARKillsZombies#6873354") # returns data of type dict
    # printing results to console
    print(profile)
asyncio.run(main())

Console Output

{'status': 'error', 'data': {'type': 'com.activision.mt.common.stdtools.exceptions.NoStackTraceException', 'message': 'Not permitted: user not found'}}

**Comment by TodoLodo** [comment]
Hey @kilgoreandy 

Thanks for mentioning this issue, we have faced this issue during our recent test runs, our dev team is working on fixing it, hopefully it wont take long and if any further issues may rise feel free to mention them here 

Thanks

**Comment by Engineer152** [comment]
This issue has been resolved in the latest version. All Activision IDs will now map correctly.
